// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIDemo.DAL;

#nullable disable

namespace WebAPIDemo.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240703160017_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDemo.Models.Shirt", b =>
                {
                    b.Property<int>("ShirtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ShirtId");

                    b.ToTable("shirts");

                    b.HasData(
                        new
                        {
                            ShirtId = 1,
                            Brand = "Nike",
                            Color = "Red",
                            Gender = "Male",
                            Price = 29.989999999999998,
                            Size = 42
                        },
                        new
                        {
                            ShirtId = 2,
                            Brand = "Adidas",
                            Color = "Blue",
                            Gender = "Female",
                            Price = 25.989999999999998,
                            Size = 40
                        },
                        new
                        {
                            ShirtId = 3,
                            Brand = "Puma",
                            Color = "Green",
                            Gender = "Male",
                            Price = 32.990000000000002,
                            Size = 44
                        },
                        new
                        {
                            ShirtId = 4,
                            Brand = "Reebok",
                            Color = "Black",
                            Gender = "Female",
                            Price = 27.989999999999998,
                            Size = 38
                        },
                        new
                        {
                            ShirtId = 5,
                            Brand = "Under Armour",
                            Color = "White",
                            Gender = "Male",
                            Price = 34.990000000000002,
                            Size = 46
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
